import type { BrandConfig } from './brand-config.js';
import { parseBrandConfig } from './brand-config.js';

export const rifaqDcleanBrandConfig: BrandConfig = parseBrandConfig({
  brandName: { ar: 'رفاق', en: 'Rifaq' },
  brandTagline: {
    ar: 'خدمات ضيافة وتنظيف ذكية بضغطة زر',
    en: 'Smart hospitality and cleaning services at your fingertips',
  },
  legalName: 'Rifaq Smart Services LLC',
  commercialRegister: '1010000000',
  vatNumber: '300000000000003',
  logoLight: 'https://assets.rifaq.example/brand/logo-light.svg',
  logoDark: 'https://assets.rifaq.example/brand/logo-dark.svg',
  logoIcon: 'https://assets.rifaq.example/brand/icon.png',
  splashScreen: 'https://assets.rifaq.example/brand/splash.png',
  colors: {
    primary: '#1F4358',
    secondary: '#356B91',
    accent: '#7EBDB0',
    background: '#FFFFFF',
    surface: '#F5F9FA',
    textPrimary: '#1A1A1A',
    textSecondary: '#5C5C5C',
    success: '#27AE60',
    danger: '#C0392B',
    warning: '#C9A961',
  },
  fonts: { arabic: 'IBM Plex Arabic', english: 'Inter' },
  currency: { code: 'SAR', symbol: 'SAR', symbolAr: 'ر.س' },
  defaultLanguage: 'ar',
  supportedLanguages: ['ar', 'en'],
  contact: {
    phone: '+966920000000',
    whatsapp: '+966500000000',
    email: 'support@rifaq.example',
    address: { ar: 'الرياض، المملكة العربية السعودية', en: 'Riyadh, Saudi Arabia' },
    workingHours: { ar: 'يومياً من 8 صباحاً حتى 10 مساءً', en: 'Daily, 8 AM to 10 PM' },
    socialMedia: {
      instagram: 'https://instagram.com/rifaq',
      twitter: 'https://x.com/rifaq',
      tiktok: 'https://tiktok.com/@rifaq',
      snapchat: 'https://snapchat.com/add/rifaq',
    },
  },
  services: [
    {
      id: '11111111-1111-4111-8111-111111111111',
      category: 'cleaning',
      nameAr: 'تنظيف منزلي',
      nameEn: 'Home Cleaning',
      descriptionAr: 'فريق تنظيف محترف للمنازل والشقق.',
      descriptionEn: 'Professional cleaning teams for homes and apartments.',
      iconUrl: 'https://assets.rifaq.example/services/home-cleaning.svg',
      basePrice: 149,
      pricingType: 'fixed',
      duration: 120,
      active: true,
      options: [
        {
          id: '21111111-1111-4111-8111-111111111111',
          nameAr: 'تعقيم إضافي',
          nameEn: 'Extra sanitization',
          price: 39,
          active: true,
        },
      ],
    },
    {
      id: '11111111-2222-4222-8222-111111111111',
      category: 'laundry',
      nameAr: 'غسيل وكي',
      nameEn: 'Laundry & Ironing',
      descriptionAr: 'استلام وتسليم الملابس مع عناية احترافية.',
      descriptionEn: 'Pickup and delivery laundry care with professional finishing.',
      iconUrl: 'https://assets.rifaq.example/services/laundry.svg',
      basePrice: 25,
      pricingType: 'per_item',
      duration: 1440,
      active: true,
      options: [],
    },
    {
      id: '11111111-3333-4333-8333-111111111111',
      category: 'locker',
      nameAr: 'بوكس ذكي',
      nameEn: 'Smart Locker',
      descriptionAr: 'تسليم واستلام ذاتي عبر البوكسات الذكية.',
      descriptionEn: 'Self-service pickup and drop-off through smart lockers.',
      iconUrl: 'https://assets.rifaq.example/services/locker.svg',
      basePrice: 15,
      pricingType: 'fixed',
      duration: 30,
      active: true,
      options: [],
    },
  ],
  serviceAreas: [{ name: 'Riyadh Core', coordinates: [24.7136, 46.6753], radius: 25000 }],
  financial: {
    vatRate: 0.15,
    minOrderValue: 50,
    deliveryFee: 15,
    freeDeliveryThreshold: 250,
  },
  features: {
    smartLockers: true,
    laundryService: true,
    subscriptions: true,
    referralProgram: true,
    loyaltyPoints: true,
    b2bAccounts: true,
    multiLanguage: true,
    walletPayment: true,
    cashOnDelivery: true,
  },
});
